production:
  solr:
    hostname: localhost
    port: 8081
    log_level: WARNING
    path: /solr/collection1
    solr_home: /usr/share/solr
    user: tomcat
    password: gic0vut8ep6as9gu
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    